namespace HeadlessDCGO.Engine.Headless.DataLoading;

using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using HeadlessDCGO.Engine.Headless.Services;

// (G6-003) Loads real card-stat data (generated by tools/CardDataConverter into the embedded
// Assets/CardBaseEntity/cards.json) into a CardDatabase as CardRecords. Replaces hand-built test
// Upserts for production / full-match scenarios. Stats land on the CardRecord (CardType / PlayCost /
// EvolutionCost) and in Metadata (color / set / level / dp / effect texts), so DP-reading systems
// (DigivolutionStackReader, CurrentDp) see real printed DP.
public static class CardBaseEntityLoader
{
    private const string ResourceSuffix = "cards.json";

    /// <summary>Load all embedded card-stat records into <paramref name="database"/>. Returns the count.</summary>
    public static int LoadInto(CardDatabase database)
    {
        ArgumentNullException.ThrowIfNull(database);

        IReadOnlyList<CardRecord> records = ReadEmbedded();
        database.UpsertRange(records);
        return records.Count;
    }

    /// <summary>A fresh CardDatabase populated from the embedded card-stat data.</summary>
    public static CardDatabase CreateDatabase()
    {
        var database = new CardDatabase();
        LoadInto(database);
        return database;
    }

    public static IReadOnlyList<CardRecord> ReadEmbedded()
    {
        Assembly assembly = typeof(CardBaseEntityLoader).Assembly;
        string? resource = assembly.GetManifestResourceNames()
            .FirstOrDefault(name => name.EndsWith(ResourceSuffix, StringComparison.Ordinal));
        if (resource is null)
        {
            return Array.Empty<CardRecord>();
        }

        using Stream stream = assembly.GetManifestResourceStream(resource)
            ?? throw new InvalidOperationException($"Embedded card data '{resource}' could not be opened.");
        List<CardJsonDto> dtos = JsonSerializer.Deserialize<List<CardJsonDto>>(stream) ?? new List<CardJsonDto>();

        var records = new List<CardRecord>(dtos.Count);
        foreach (CardJsonDto dto in dtos)
        {
            if (string.IsNullOrWhiteSpace(dto.CardNumber))
            {
                continue;
            }

            records.Add(ToRecord(dto));
        }

        return records;
    }

    private static CardRecord ToRecord(CardJsonDto dto)
    {
        var metadata = new Dictionary<string, object?>(StringComparer.Ordinal)
        {
            ["set"] = dto.Set,
            ["color"] = dto.Color,
            ["level"] = dto.Level,
            ["dp"] = dto.Dp,
        };
        if (!string.IsNullOrWhiteSpace(dto.Effect)) metadata["effect"] = dto.Effect;
        if (!string.IsNullOrWhiteSpace(dto.InheritedEffect)) metadata["inheritedEffect"] = dto.InheritedEffect;
        if (!string.IsNullOrWhiteSpace(dto.SecurityEffect)) metadata["securityEffect"] = dto.SecurityEffect;
        if (!string.IsNullOrWhiteSpace(dto.EffectClass)) metadata["effectClass"] = dto.EffectClass;

        return new CardRecord(
            new HeadlessEntityId(dto.CardNumber),
            dto.CardNumber,
            string.IsNullOrWhiteSpace(dto.Name) ? dto.CardNumber : dto.Name,
            metadata,
            CardType: string.IsNullOrWhiteSpace(dto.CardType) ? null : dto.CardType,
            PlayCost: dto.PlayCost,
            EvolutionCost: dto.EvolutionCost);
    }

    public sealed class CardJsonDto
    {
        [JsonPropertyName("cardNumber")] public string CardNumber { get; set; } = string.Empty;
        [JsonPropertyName("name")] public string Name { get; set; } = string.Empty;
        [JsonPropertyName("cardType")] public string CardType { get; set; } = string.Empty;
        [JsonPropertyName("set")] public string Set { get; set; } = string.Empty;
        [JsonPropertyName("color")] public string Color { get; set; } = string.Empty;
        [JsonPropertyName("level")] public int Level { get; set; }
        [JsonPropertyName("playCost")] public int? PlayCost { get; set; }
        [JsonPropertyName("evolutionCost")] public int? EvolutionCost { get; set; }
        [JsonPropertyName("dp")] public int Dp { get; set; }
        [JsonPropertyName("effect")] public string? Effect { get; set; }
        [JsonPropertyName("inheritedEffect")] public string? InheritedEffect { get; set; }
        [JsonPropertyName("securityEffect")] public string? SecurityEffect { get; set; }
        [JsonPropertyName("effectClass")] public string? EffectClass { get; set; }
    }
}
