using System.Text;
using HeadlessDCGO.Engine.Headless.Bridge;
using HeadlessDCGO.Engine.Headless.DataLoading;
using HeadlessDCGO.Engine.Headless.Diagnostics;
using HeadlessDCGO.Engine.Headless.Runtime;
using HeadlessDCGO.Engine.Headless.Services;

// G13-003: random-legal self-play smoke over the REAL ported card pool (cards.json / CardBaseEntity).
// Both players are driven by a masked-random policy through full games built from real ST1/ST2/ST3
// starter-set cards, so ported effects auto-register and fire LIVE (CardEffectRegistrar on play). This is
// the freeze PREREQUISITE: it proves the engine loop runs real card content end-to-end without crashing,
// generating illegal actions, deadlocking, or failing to converge (FlowExceededIterationCap), and that the
// same seeds reproduce the same game (determinism a trainer depends on).
//
// Why match-level driving: a security skill (etc.) hands the choice to the DEFENDER mid-attack, so the
// acting player is "whoever currently has legal actions", not a fixed perspective. We pick the mover from
// match.GetLegalActions and apply through the RL env (which yields the RlStepResult a trainer would see).

HeadlessPlayerId P1 = new(1);
HeadlessPlayerId P2 = new(2);

// Opt-in verbose play log: `SELFPLAY_LOG=1 dotnet run ...` dumps a step-by-step log (turn/phase, mover,
// action, resulting events) for every game. Off in the regression gate so it stays quiet.
bool verbose = Environment.GetEnvironmentVariable("SELFPLAY_LOG") == "1";

// Each row: P1 set, P2 set, env seed, policy seed, step cap. Real ST1/ST2/ST3 starter decks (50 main +
// 4 digitama) — every cross-set matchup. Games terminate naturally via security depletion (combat), not a
// truncated deck-out, so they are genuine starter-deck matchups end to end.
var games = new (string P1Set, string P2Set, int EnvSeed, int PolicySeed, int Cap)[]
{
    ("ST1", "ST2", 101, 11, 800),
    ("ST2", "ST3", 202, 22, 800),
    ("ST3", "ST1", 303, 33, 800),
    ("ST1", "ST3", 404, 44, 800),
    ("ST2", "ST1", 505, 55, 800),
};

var stats = new List<GameStat>();
string? hardFailure = null;
try
{
    foreach (var g in games)
        stats.Add(await RunGameAsync(g.P1Set, g.P2Set, g.EnvSeed, g.PolicySeed, g.Cap, verbose));
}
catch (Exception ex)
{
    hardFailure = $"{ex.GetType().Name}: {ex.Message}\n{ex.StackTrace}";
}

// --- Report --------------------------------------------------------------
Console.WriteLine("matchup        steps  term  winner  plays  effects  attacks  security  flowCap  invalid");
foreach (var s in stats)
    Console.WriteLine($"{s.Matchup,-13} {s.Steps,6} {(s.Terminal ? "  Y" : "  .")}  {s.Winner,-6} {s.Plays,6} {s.EffectResolved,8} {s.Attacks,8} {s.Security,9} {(s.FlowCap ? "Y" : "."),8} {s.Invalid,8}");

if (hardFailure is not null)
{
    Console.Error.WriteLine($"\nFAIL G13-003 (exception during self-play)\n{hardFailure}");
    Environment.Exit(1);
}

// --- Assertions ----------------------------------------------------------
var failures = new List<string>();
void Check(bool ok, string label) { if (!ok) failures.Add(label); }

Check(stats.All(s => s.Invalid == 0), "no illegal action was ever generated by the masked rollout");
Check(stats.All(s => !s.FlowCap), "engine flow always converged (no FlowExceededIterationCap)");
Check(stats.All(s => !s.Deadlock), "no game deadlocked (a mover always existed until terminal)");
Check(stats.All(s => s.Steps > 0), "every game took at least one step");
Check(stats.Any(s => s.Terminal && s.Winner is "1" or "2"), "at least one game reached a real terminal with a winner (security depletion)");
Check(stats.Sum(s => s.Plays) > 0, "real cards were actually played/digivolved/activated across the games");
Check(stats.Sum(s => s.Attacks) > 0, "combat ran (attacks were declared)");
Check(stats.Sum(s => s.EffectResolved) > 0, "ported effects resolved live");
Check(stats.All(s => s.RewardOk), "terminal reward is in {-1,0,1}");

// Determinism: the first game replayed with the same seeds reproduces the same trajectory.
var replay = await RunGameAsync("ST1", "ST2", 101, 11, 800);
Check(replay.Fingerprint == stats[0].Fingerprint, "same seeds reproduce an identical trajectory (determinism)");

if (failures.Count > 0)
{
    Console.Error.WriteLine($"\nFAIL G13-003 ({failures.Count} property/properties):");
    foreach (var f in failures) Console.Error.WriteLine($"  - {f}");
    Environment.Exit(1);
}

Console.WriteLine($"\nPASS G13-003: {stats.Count} real-card self-play games ran clean (legal, convergent, deterministic).");

// --- Rollout -------------------------------------------------------------

async Task<GameStat> RunGameAsync(string p1Set, string p2Set, int envSeed, int policySeed, int cap, bool log = false)
{
    EngineContext context = EngineContext.CreateDefault(randomSeed: envSeed);
    var db = (CardDatabase)context.CardRepository;
    CardBaseEntityLoader.LoadInto(db);

    StarterDecks.StarterDeck d1 = StarterDecks.Get(p1Set), d2 = StarterDecks.Get(p2Set);
    MatchSetupConfig setup = MatchSetupConfig.Create(
        new[]
        {
            new PlayerDeckSetup(P1, d1.MainDefinitions, d1.DigitamaDefinitions),
            new PlayerDeckSetup(P2, d2.MainDefinitions, d2.DigitamaDefinitions),
        }, firstPlayerId: P1);
    MatchConfig config = MatchConfig.Create(new[] { P1, P2 }, randomSeed: envSeed, setup: setup);

    var match = new DcgoMatch(context, new EngineTrace(), actionLegality: new LegalActionSetValidator());
    var env = new HeadlessRlEnvironment(match);
    await env.InitializeAsync(config);

    var rng = new Random(policySeed);
    var players = new[] { P1, P2 };
    var counts = new Dictionary<GameEventType, int>();
    var fp = new StringBuilder();
    bool flowCap = false, deadlock = false, terminal = false, rewardOk = true;
    int steps = 0, invalid = 0, plays = 0;
    string winner = "-";

    if (log) Console.WriteLine($"\n===== GAME {p1Set} (P1) vs {p2Set} (P2)  [starter decks 50+4]  envSeed={envSeed} policySeed={policySeed} =====");

    while (steps < cap && !match.IsTerminal())
    {
        HeadlessPlayerId mover = default;
        bool found = false;
        foreach (var p in players)
        {
            if (match.GetLegalActions(p).Count > 0) { mover = p; found = true; break; }
        }
        if (!found) { deadlock = true; break; }

        IReadOnlyList<LegalAction> legal = match.GetLegalActions(mover);
        LegalAction action = legal[rng.Next(legal.Count)];
        if (IsPlay(action.ActionType)) plays++;

        HeadlessTurnState turn = match.GetObservation().Turn;
        RlStepResult st = await env.StepAsync(action);
        steps++;

        foreach (GameEvent ev in st.Events)
        {
            counts[ev.Type] = counts.GetValueOrDefault(ev.Type) + 1;
            if (ev.Type == GameEventType.InvalidAction) invalid++;
        }
        if (st.FlowExceededIterationCap) flowCap = true;
        fp.Append(action.Id.Value).Append(st.IsTerminal ? "#T" : "#.").Append(';');

        if (log)
        {
            string detail = string.Join(" / ", st.Events
                .Where(e => e.Type is GameEventType.EffectResolved or GameEventType.AttackDeclared
                    or GameEventType.AttackResolved or GameEventType.SecurityCheck or GameEventType.SecuritySkill
                    or GameEventType.ChoiceRequested or GameEventType.ChoiceResolved or GameEventType.GameEnded)
                .Select(e => e.Message));
            int mem = match.GetObservation().Memory.Current;
            Console.WriteLine(
                $"  {steps,4}. T{turn.TurnNumber,-2} {turn.AsIsPhaseName,-12} P{mover.Value} mem={mem,3} {action.ActionType,-14} {Tail(action.Id.Value)}"
                + (detail.Length > 0 ? $"   => {detail}" : ""));
        }

        if (st.IsTerminal)
        {
            terminal = true;
            if (st.Result is { } r)
                winner = r.IsDraw ? "draw" : (r.WinnerId?.Value.ToString() ?? "?");
            rewardOk = st.Reward is -1d or 0d or 1d;
            if (log) Console.WriteLine($"  ---- TERMINAL: winner=P{winner}, reward(P1-perspective)={st.Reward}, reason={(st.Result?.Reason ?? "?")}");
            break;
        }
    }

    int C(GameEventType t) => counts.GetValueOrDefault(t);
    return new GameStat(
        $"{p1Set}v{p2Set}", steps, terminal, winner,
        plays, C(GameEventType.EffectResolved), C(GameEventType.AttackDeclared),
        C(GameEventType.SecurityCheck), flowCap, deadlock, invalid, rewardOk, fp.ToString());
}

static string Tail(string actionId)
{
    // The action id encodes type:card:target… — keep it short but show the card/target payload.
    string s = actionId.Length <= 60 ? actionId : "…" + actionId[^59..];
    return s;
}

static bool IsPlay(string actionType) =>
    actionType is HeadlessActionTypes.PlayCard or HeadlessActionTypes.Digivolve
        or HeadlessActionTypes.SpecialPlay or HeadlessActionTypes.ActivateOption
        or HeadlessActionTypes.HatchDigitama or HeadlessActionTypes.MoveBreedingToBattle;

internal sealed record GameStat(
    string Matchup, int Steps, bool Terminal, string Winner,
    int Plays, int EffectResolved, int Attacks, int Security,
    bool FlowCap, bool Deadlock, int Invalid, bool RewardOk, string Fingerprint);
