using System.Text;
using HeadlessDCGO.Engine.Headless.Bridge;
using HeadlessDCGO.Engine.Headless.DataLoading;
using HeadlessDCGO.Engine.Headless.Diagnostics;
using HeadlessDCGO.Engine.Headless.Runtime;
using HeadlessDCGO.Engine.Headless.Services;

// G13-003: random-legal self-play smoke over the REAL ported card pool (cards.json / CardBaseEntity).
// Both players are driven by a masked-random policy through full games built from real ST1/ST2/ST3
// starter-set cards, so ported effects auto-register and fire LIVE (CardEffectRegistrar on play). This is
// the freeze PREREQUISITE: it proves the engine loop runs real card content end-to-end without crashing,
// generating illegal actions, deadlocking, or failing to converge (FlowExceededIterationCap), and that the
// same seeds reproduce the same game (determinism a trainer depends on).
//
// Why match-level driving: a security skill (etc.) hands the choice to the DEFENDER mid-attack, so the
// acting player is "whoever currently has legal actions", not a fixed perspective. We pick the mover from
// match.GetLegalActions and apply through the RL env (which yields the RlStepResult a trainer would see).

HeadlessPlayerId P1 = new(1);
HeadlessPlayerId P2 = new(2);

// Opt-in verbose play log: `SELFPLAY_LOG=1 dotnet run ...` dumps a step-by-step log (turn/phase, mover,
// action, resulting events) for every game. Off in the regression gate so it stays quiet.
bool verbose = Environment.GetEnvironmentVariable("SELFPLAY_LOG") == "1";

// Each row: P1 set, P2 set, main-deck size, digitama size, env seed, policy seed, step cap, expect terminal.
var games = new (string P1Set, string P2Set, int Main, int Egg, int EnvSeed, int PolicySeed, int Cap, bool ExpectTerminal)[]
{
    // Long random games over full-size real decks — stability over hundreds of decisions.
    ("ST1", "ST2", 40, 4, 101, 11, 600, false),
    ("ST2", "ST3", 40, 4, 202, 22, 600, false),
    ("ST3", "ST1", 40, 4, 303, 33, 600, false),
    // Short real decks (10 main -> 5 hand + 5 security + 0 library) deck out fast -> a real terminal+winner.
    ("ST1", "ST2", 10, 3, 404, 44, 300, true),
    ("ST3", "ST1", 10, 3, 505, 55, 300, true),
};

var stats = new List<GameStat>();
string? hardFailure = null;
try
{
    foreach (var g in games)
        stats.Add(await RunGameAsync(g.P1Set, g.P2Set, g.Main, g.Egg, g.EnvSeed, g.PolicySeed, g.Cap, g.ExpectTerminal, verbose));
}
catch (Exception ex)
{
    hardFailure = $"{ex.GetType().Name}: {ex.Message}\n{ex.StackTrace}";
}

// --- Report --------------------------------------------------------------
Console.WriteLine("matchup        steps  term  winner  plays  effects  attacks  security  flowCap  invalid");
foreach (var s in stats)
    Console.WriteLine($"{s.Matchup,-13} {s.Steps,6} {(s.Terminal ? "  Y" : "  .")}  {s.Winner,-6} {s.Plays,6} {s.EffectResolved,8} {s.Attacks,8} {s.Security,9} {(s.FlowCap ? "Y" : "."),8} {s.Invalid,8}");

if (hardFailure is not null)
{
    Console.Error.WriteLine($"\nFAIL G13-003 (exception during self-play)\n{hardFailure}");
    Environment.Exit(1);
}

// --- Assertions ----------------------------------------------------------
var failures = new List<string>();
void Check(bool ok, string label) { if (!ok) failures.Add(label); }

Check(stats.All(s => s.Invalid == 0), "no illegal action was ever generated by the masked rollout");
Check(stats.All(s => !s.FlowCap), "engine flow always converged (no FlowExceededIterationCap)");
Check(stats.All(s => !s.Deadlock), "no game deadlocked (a mover always existed until terminal)");
Check(stats.All(s => s.Steps > 0), "every game took at least one step");
Check(stats.Where(s => s.ExpectTerminal).All(s => s.Terminal), "every short-deck game reached a real terminal");
Check(stats.Any(s => s.Terminal && s.Winner is "1" or "2"), "at least one game produced a concrete winner");
Check(stats.Sum(s => s.Plays) > 0, "real cards were actually played/digivolved/activated across the games");
Check(stats.Sum(s => s.Attacks) > 0, "combat ran (attacks were declared)");
Check(stats.Sum(s => s.EffectResolved) > 0, "ported effects resolved live");
Check(stats.All(s => s.RewardOk), "terminal reward is in {-1,0,1}");

// Determinism: the first game replayed with the same seeds reproduces the same trajectory.
var replay = await RunGameAsync("ST1", "ST2", 40, 4, 101, 11, 600, false);
Check(replay.Fingerprint == stats[0].Fingerprint, "same seeds reproduce an identical trajectory (determinism)");

if (failures.Count > 0)
{
    Console.Error.WriteLine($"\nFAIL G13-003 ({failures.Count} property/properties):");
    foreach (var f in failures) Console.Error.WriteLine($"  - {f}");
    Environment.Exit(1);
}

Console.WriteLine($"\nPASS G13-003: {stats.Count} real-card self-play games ran clean (legal, convergent, deterministic).");

// --- Rollout -------------------------------------------------------------

async Task<GameStat> RunGameAsync(string p1Set, string p2Set, int mainSize, int eggSize, int envSeed, int policySeed, int cap, bool expectTerminal, bool log = false)
{
    EngineContext context = EngineContext.CreateDefault(randomSeed: envSeed);
    var db = (CardDatabase)context.CardRepository;
    CardBaseEntityLoader.LoadInto(db);

    (var m1, var e1) = BuildDeck(db, p1Set, P1, mainSize, eggSize);
    (var m2, var e2) = BuildDeck(db, p2Set, P2, mainSize, eggSize);
    MatchSetupConfig setup = MatchSetupConfig.Create(
        new[] { new PlayerDeckSetup(P1, m1, e1), new PlayerDeckSetup(P2, m2, e2) }, firstPlayerId: P1);
    MatchConfig config = MatchConfig.Create(new[] { P1, P2 }, randomSeed: envSeed, setup: setup);

    var match = new DcgoMatch(context, new EngineTrace(), actionLegality: new LegalActionSetValidator());
    var env = new HeadlessRlEnvironment(match);
    await env.InitializeAsync(config);

    var rng = new Random(policySeed);
    var players = new[] { P1, P2 };
    var counts = new Dictionary<GameEventType, int>();
    var fp = new StringBuilder();
    bool flowCap = false, deadlock = false, terminal = false, rewardOk = true;
    int steps = 0, invalid = 0, plays = 0;
    string winner = "-";

    if (log) Console.WriteLine($"\n===== GAME {p1Set} (P1) vs {p2Set} (P2)  main={mainSize} envSeed={envSeed} policySeed={policySeed} =====");

    while (steps < cap && !match.IsTerminal())
    {
        HeadlessPlayerId mover = default;
        bool found = false;
        foreach (var p in players)
        {
            if (match.GetLegalActions(p).Count > 0) { mover = p; found = true; break; }
        }
        if (!found) { deadlock = true; break; }

        IReadOnlyList<LegalAction> legal = match.GetLegalActions(mover);
        LegalAction action = legal[rng.Next(legal.Count)];
        if (IsPlay(action.ActionType)) plays++;

        HeadlessTurnState turn = match.GetObservation().Turn;
        RlStepResult st = await env.StepAsync(action);
        steps++;

        foreach (GameEvent ev in st.Events)
        {
            counts[ev.Type] = counts.GetValueOrDefault(ev.Type) + 1;
            if (ev.Type == GameEventType.InvalidAction) invalid++;
        }
        if (st.FlowExceededIterationCap) flowCap = true;
        fp.Append(action.Id.Value).Append(st.IsTerminal ? "#T" : "#.").Append(';');

        if (log)
        {
            string detail = string.Join(" / ", st.Events
                .Where(e => e.Type is GameEventType.EffectResolved or GameEventType.AttackDeclared
                    or GameEventType.AttackResolved or GameEventType.SecurityCheck or GameEventType.SecuritySkill
                    or GameEventType.ChoiceRequested or GameEventType.ChoiceResolved or GameEventType.GameEnded)
                .Select(e => e.Message));
            int mem = match.GetObservation().Memory.Current;
            Console.WriteLine(
                $"  {steps,4}. T{turn.TurnNumber,-2} {turn.AsIsPhaseName,-12} P{mover.Value} mem={mem,3} {action.ActionType,-14} {Tail(action.Id.Value)}"
                + (detail.Length > 0 ? $"   => {detail}" : ""));
        }

        if (st.IsTerminal)
        {
            terminal = true;
            if (st.Result is { } r)
                winner = r.IsDraw ? "draw" : (r.WinnerId?.Value.ToString() ?? "?");
            rewardOk = st.Reward is -1d or 0d or 1d;
            if (log) Console.WriteLine($"  ---- TERMINAL: winner=P{winner}, reward(P1-perspective)={st.Reward}, reason={(st.Result?.Reason ?? "?")}");
            break;
        }
    }

    int C(GameEventType t) => counts.GetValueOrDefault(t);
    return new GameStat(
        $"{p1Set}v{p2Set}({mainSize})", steps, terminal, winner,
        plays, C(GameEventType.EffectResolved), C(GameEventType.AttackDeclared),
        C(GameEventType.SecurityCheck), flowCap, deadlock, invalid, rewardOk, expectTerminal, fp.ToString());
}

static string Tail(string actionId)
{
    // The action id encodes type:card:target… — keep it short but show the card/target payload.
    string s = actionId.Length <= 60 ? actionId : "…" + actionId[^59..];
    return s;
}

static bool IsPlay(string actionType) =>
    actionType is HeadlessActionTypes.PlayCard or HeadlessActionTypes.Digivolve
        or HeadlessActionTypes.SpecialPlay or HeadlessActionTypes.ActivateOption
        or HeadlessActionTypes.HatchDigitama or HeadlessActionTypes.MoveBreedingToBattle;

static (HeadlessEntityId[] Main, HeadlessEntityId[] Egg) BuildDeck(
    CardDatabase db, string setPrefix, HeadlessPlayerId _, int mainSize, int eggSize)
{
    var mainPool = new List<HeadlessEntityId>();
    var eggPool = new List<HeadlessEntityId>();
    for (int i = 1; i <= 16; i++)
    {
        var id = new HeadlessEntityId($"{setPrefix}_{i:D2}");
        if (db.TryGetCard(id, out CardRecord? rec) && rec is not null)
            (string.Equals(rec.CardType, "DigiEgg", StringComparison.Ordinal) ? eggPool : mainPool).Add(id);
    }
    if (mainPool.Count == 0) throw new InvalidOperationException($"{setPrefix}: no main-deck cards found in the real card pool.");
    if (eggPool.Count == 0) throw new InvalidOperationException($"{setPrefix}: no DigiEgg found in the real card pool.");

    var main = Enumerable.Range(0, mainSize).Select(k => mainPool[k % mainPool.Count]).ToArray();
    var egg = Enumerable.Range(0, eggSize).Select(k => eggPool[k % eggPool.Count]).ToArray();
    return (main, egg);
}

internal sealed record GameStat(
    string Matchup, int Steps, bool Terminal, string Winner,
    int Plays, int EffectResolved, int Attacks, int Security,
    bool FlowCap, bool Deadlock, int Invalid, bool RewardOk, bool ExpectTerminal, string Fingerprint);
